//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspCitylink.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int StoreId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Product StoreProduct { get; set; }
    }
}
